name: cartesian_vision
description: An image preprocessing framework.
version: 0.0.1
# homepage: https://www.example.com
repository: https://github.com/ReneMuala/cartesian_vision

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  image: ^3.2.0
